# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "unicode_scanner"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Morgan"]
  s.date = "2012-07-12"
  s.description = "An implementation of StringScanner that doesn't split multibyte characters."
  s.email = "git@timothymorgan.info"
  s.extra_rdoc_files = [
      "LICENSE.txt",
      "README.md"
  ]
  s.files = [
      ".document",
      ".rspec",
      ".rvmrc",
      "Gemfile",
      "Gemfile.lock",
      "LICENSE.txt",
      "README.md",
      "Rakefile",
      "VERSION",
      "lib/unicode_scanner.rb",
      "spec/spec_helper.rb",
      "spec/unicode_scanner_spec.rb",
      "unicode_scanner.gemspec"
  ]
  s.homepage = "http://github.com/RISCfuture/unicode_scanner"
  s.licenses = %w[MIT]
  s.require_paths = %w[lib]
  s.rubygems_version = "1.8.24"
  s.summary = "Unicode-aware implementation of StringScanner"

  if s.respond_to? :specification_version
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_development_dependency('bundler', [">= 0"])
      s.add_development_dependency('jeweler', [">= 0"])
      s.add_development_dependency('redcarpet', [">= 0"])
      s.add_development_dependency('rspec', [">= 0"])
      s.add_development_dependency('yard', [">= 0"])
    else
      s.add_dependency('bundler', [">= 0"])
      s.add_dependency('jeweler', [">= 0"])
      s.add_dependency('redcarpet', [">= 0"])
      s.add_dependency('rspec', [">= 0"])
      s.add_dependency('yard', [">= 0"])
    end
  else
    s.add_dependency('rspec', [">= 0"])
    s.add_dependency('rspec', [">= 0"])
    s.add_dependency('yard', [">= 0"])
    s.add_dependency('yard', [">= 0"])
    s.add_dependency('yard', [">= 0"])
  end
end
